# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_lib.texas_pb2 as texas__pb2


class TexasStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UserLogin = channel.unary_unary(
                '/texas.Texas/UserLogin',
                request_serializer=texas__pb2.UserInfo.SerializeToString,
                response_deserializer=texas__pb2.ActionResponse.FromString,
                )
        self.UserRegister = channel.unary_unary(
                '/texas.Texas/UserRegister',
                request_serializer=texas__pb2.UserInfo.SerializeToString,
                response_deserializer=texas__pb2.ActionResponse.FromString,
                )
        self.GetStatus = channel.unary_unary(
                '/texas.Texas/GetStatus',
                request_serializer=texas__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=texas__pb2.GetStatusResponse.FromString,
                )
        self.Action = channel.unary_unary(
                '/texas.Texas/Action',
                request_serializer=texas__pb2.ActionRequest.SerializeToString,
                response_deserializer=texas__pb2.ActionResponse.FromString,
                )
        self.CreateRoom = channel.unary_unary(
                '/texas.Texas/CreateRoom',
                request_serializer=texas__pb2.CreateRoomRequest.SerializeToString,
                response_deserializer=texas__pb2.RoomResponse.FromString,
                )
        self.GetinRoom = channel.unary_unary(
                '/texas.Texas/GetinRoom',
                request_serializer=texas__pb2.GetinRoomRequest.SerializeToString,
                response_deserializer=texas__pb2.RoomResponse.FromString,
                )


class TexasServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UserLogin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserRegister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Action(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetinRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TexasServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UserLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.UserLogin,
                    request_deserializer=texas__pb2.UserInfo.FromString,
                    response_serializer=texas__pb2.ActionResponse.SerializeToString,
            ),
            'UserRegister': grpc.unary_unary_rpc_method_handler(
                    servicer.UserRegister,
                    request_deserializer=texas__pb2.UserInfo.FromString,
                    response_serializer=texas__pb2.ActionResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=texas__pb2.GetStatusRequest.FromString,
                    response_serializer=texas__pb2.GetStatusResponse.SerializeToString,
            ),
            'Action': grpc.unary_unary_rpc_method_handler(
                    servicer.Action,
                    request_deserializer=texas__pb2.ActionRequest.FromString,
                    response_serializer=texas__pb2.ActionResponse.SerializeToString,
            ),
            'CreateRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRoom,
                    request_deserializer=texas__pb2.CreateRoomRequest.FromString,
                    response_serializer=texas__pb2.RoomResponse.SerializeToString,
            ),
            'GetinRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetinRoom,
                    request_deserializer=texas__pb2.GetinRoomRequest.FromString,
                    response_serializer=texas__pb2.RoomResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'texas.Texas', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Texas(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UserLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/texas.Texas/UserLogin',
            texas__pb2.UserInfo.SerializeToString,
            texas__pb2.ActionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UserRegister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/texas.Texas/UserRegister',
            texas__pb2.UserInfo.SerializeToString,
            texas__pb2.ActionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/texas.Texas/GetStatus',
            texas__pb2.GetStatusRequest.SerializeToString,
            texas__pb2.GetStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Action(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/texas.Texas/Action',
            texas__pb2.ActionRequest.SerializeToString,
            texas__pb2.ActionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/texas.Texas/CreateRoom',
            texas__pb2.CreateRoomRequest.SerializeToString,
            texas__pb2.RoomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetinRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/texas.Texas/GetinRoom',
            texas__pb2.GetinRoomRequest.SerializeToString,
            texas__pb2.RoomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
